on: 
  issue_comment:
    types: [created]

jobs:
  pr_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment '${{ github.event.comment }}'"
